services:
  weatherforecastconsumersyncdatabases:
    image: distributed/weatherforecastconsumersyncdatabases:latest
    build:
      context: ../src
      dockerfile: weatherForecastSyncConsumerDockerfile