services:
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD_SKELETON}
    volumes:
      - redis_data:/data
    
volumes:
  redis_data:
  