services:
  usersapi:
    image: distributed/usersapi:latest
    container_name: usersapi
    restart: always
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${USERS_ASPNETCORE_Kestrel__Certificates__Default__Path}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${USERS_ASPNETCORE_Kestrel__Certificates__Default__Password}
      - ASPNETCORE_ENVIRONMENT=${USERS_ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=${USERS_ASPNETCORE_URLS}
      - AppName=${USERS_AppName}
      - keysFolder=${USERS_keysFolder}
      - ConnectionStrings__OpenTelemetry
    ports:
      - "8550:80"
      - "8551:443"
    volumes:
      - dotnetapp_keys_data:${USERS_keysFolder}

volumes:
  dotnetapp_keys_data:
