services:
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      - REDIS_PASSWORD
    volumes:
      - redis_data:/data
    
volumes:
  redis_data:
  